#!/bin/sh

export IFS=' 	
'
SYSPATH=$(command -p getconf PATH 2>/dev/null)
export PATH="${SYSPATH:-/bin:/usr/bin}${PATH:+:$PATH}"
export LC_ALL=C
progname=$(basename "$0")

usage(){
	cat <<EOF
usage: $progname [file...]
EOF
}
print_help(){
	usage
	cat <<EOF

OPTIONS
	-h	print this help
EOF
}
error(){
	printf '%s: %s\n\n' "$progname" "$1" 1>&2
	usage 1>&2
	exit ${2:-1}
}

# for sed 
LF='
'
CR=$(printf '\r')
# marker of original newline.
GS=$(printf '\035') 
# used as field separater in inter
RS=$(printf '\036')

while getopts h opt; do
	case "$opt" in
	h)	print_help;exit 0;;
	?)	usage 1>&2;exit 1;;
	esac
done
shift $((OPTIND - 1))

cat -- ${1+"$@"} |
	sed -- '
		s/\\/\\\\/g
		s/'"$CR"'/\\r/g
		s/$/'"$GS"'/
		s:</\{0,1\}[0-9a-zA-Z]\{1,\}:\'"$LF"'&\'"$LF"':g
		s:['\''">=]:\'"$LF"'&\'"$LF"':g' |
	sed '/^$/d' |
	#
	# categorize strings into types
	# types
	# - startTag
	# - attrName
	# - attrVal
	# - endTag
	# - voidElement
	# - text
	#
	awk -v fieldSep="$RS" -v newline="$GS" -f lib/lexer.awk |
	awk -F "$RS" '
		BEGIN{
		}
		{
			print $1,$2
		}' |
	sed 's/'"$GS"'/\\n/g'
